#############################################################################
# Makefile for building: ithome
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 9 22:37:08 2014
# Project:  ithome.pro
# Template: app
# Command: d:/qt/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQ_OS_HARMATTAN -DHARMATTAN_BOOSTER -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtWebKit -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSystemInfo -Iqmlapplicationviewer -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,D:/usr/lib
LIBS          = $(SUBLIBS)  -LD:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -pie -rdynamic -lmdeclarativecache -L/usr/lib -lQtSystemInfo -lQtDeclarative -lQtWebKit -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = d:/qt/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		setcss.cpp \
		myimage.cpp \
		cachecontent.cpp \
		settings.cpp \
		netinfo.cpp \
		isclick.cpp \
		utility.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc/moc_qmlapplicationviewer.cpp \
		moc/moc_setcss.cpp \
		moc/moc_myimage.cpp \
		moc/moc_cachecontent.cpp \
		moc/moc_settings.cpp \
		moc/moc_netinfo.cpp \
		moc/moc_isclick.cpp \
		moc/moc_utility.cpp \
		rcc/qrc_image.cpp
OBJECTS       = obj/main.o \
		obj/setcss.o \
		obj/myimage.o \
		obj/cachecontent.o \
		obj/settings.o \
		obj/netinfo.o \
		obj/isclick.o \
		obj/utility.o \
		obj/qmlapplicationviewer.o \
		obj/moc_qmlapplicationviewer.o \
		obj/moc_setcss.o \
		obj/moc_myimage.o \
		obj/moc_cachecontent.o \
		obj/moc_settings.o \
		obj/moc_netinfo.o \
		obj/moc_isclick.o \
		obj/moc_utility.o \
		obj/qrc_image.o
DIST          = ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		ithome.pro
QMAKE_TARGET  = ithome
DESTDIR       = 
TARGET        = ithome

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ithome.pro  ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl \
		d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl:
d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
d:/qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qt/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/ithome1.0.0 || $(MKDIR) obj/ithome1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/ithome1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h setcss.h myimage.h cachecontent.h settings.h netinfo.h isclick.h utility.h obj/ithome1.0.0/ && $(COPY_FILE) --parents image.qrc obj/ithome1.0.0/ && $(COPY_FILE) --parents main.cpp setcss.cpp myimage.cpp cachecontent.cpp settings.cpp netinfo.cpp isclick.cpp utility.cpp qmlapplicationviewer/qmlapplicationviewer.cpp obj/ithome1.0.0/ && (cd `dirname obj/ithome1.0.0` && $(TAR) ithome1.0.0.tar ithome1.0.0 && $(COMPRESS) ithome1.0.0.tar) && $(MOVE) `dirname obj/ithome1.0.0`/ithome1.0.0.tar.gz . && $(DEL_FILE) -r obj/ithome1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qmlapplicationviewer.cpp moc/moc_setcss.cpp moc/moc_myimage.cpp moc/moc_cachecontent.cpp moc/moc_settings.cpp moc/moc_netinfo.cpp moc/moc_isclick.cpp moc/moc_utility.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qmlapplicationviewer.cpp moc/moc_setcss.cpp moc/moc_myimage.cpp moc/moc_cachecontent.cpp moc/moc_settings.cpp moc/moc_netinfo.cpp moc/moc_isclick.cpp moc/moc_utility.cpp
moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc/moc_qmlapplicationviewer.cpp

moc/moc_setcss.cpp: setcss.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) setcss.h -o moc/moc_setcss.cpp

moc/moc_myimage.cpp: settings.h \
		myimage.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) myimage.h -o moc/moc_myimage.cpp

moc/moc_cachecontent.cpp: settings.h \
		cachecontent.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) cachecontent.h -o moc/moc_cachecontent.cpp

moc/moc_settings.cpp: settings.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) settings.h -o moc/moc_settings.cpp

moc/moc_netinfo.cpp: netinfo.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) netinfo.h -o moc/moc_netinfo.cpp

moc/moc_isclick.cpp: isclick.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) isclick.h -o moc/moc_isclick.cpp

moc/moc_utility.cpp: utility.h
	D:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) utility.h -o moc/moc_utility.cpp

compiler_rcc_make_all: rcc/qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_image.cpp
rcc/qrc_image.cpp: image.qrc \
		Image/02.png \
		Image/03.png \
		Image/MeeGo.png \
		Image/comment_meego.svg \
		Image/search.svg \
		Image/pull_down_inverse.svg \
		Image/tb_menu.svg \
		Image/tieba.svg \
		Image/edit.svg \
		Image/divide.png \
		Image/quit.svg \
		Image/shadow.png \
		Image/04.png \
		Image/upmeego.svg \
		Image/refresh.svg \
		Image/comment.svg \
		Image/refresh2.svg \
		Image/up.svg \
		Image/back.svg \
		Image/Browser.svg \
		Image/search2.svg \
		Image/ist_indicator.svg \
		Image/tencent_Weibo.svg \
		Image/comment2.svg \
		Image/setting2.svg \
		Image/ithome_logo.png \
		Image/edit2.svg \
		Image/Symbian.png \
		Image/PageHeader.svg \
		Image/highlight.svg \
		Image/share2.svg \
		Image/share.svg \
		Image/Wechat.svg \
		Image/comment2_meego.svg \
		Image/01.png \
		Image/upsymbian.svg \
		Image/quit2.svg \
		Image/Qzone.svg \
		Image/Copy.svg \
		Image/back2.svg \
		Image/pull_down.svg \
		Image/it.png \
		Image/Sina_Weibo.svg \
		Image/toolbar.svg \
		Image/setting.svg
	d:/qt/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name image image.qrc -o rcc/qrc_image.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/main.o: main.cpp setcss.h \
		myimage.h \
		settings.h \
		cachecontent.h \
		netinfo.h \
		isclick.h \
		utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/setcss.o: setcss.cpp setcss.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/setcss.o setcss.cpp

obj/myimage.o: myimage.cpp myimage.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/myimage.o myimage.cpp

obj/cachecontent.o: cachecontent.cpp cachecontent.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cachecontent.o cachecontent.cpp

obj/settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settings.o settings.cpp

obj/netinfo.o: netinfo.cpp netinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/netinfo.o netinfo.cpp

obj/isclick.o: isclick.cpp isclick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/isclick.o isclick.cpp

obj/utility.o: utility.cpp utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/utility.o utility.cpp

obj/qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

obj/moc_qmlapplicationviewer.o: moc/moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qmlapplicationviewer.o moc/moc_qmlapplicationviewer.cpp

obj/moc_setcss.o: moc/moc_setcss.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_setcss.o moc/moc_setcss.cpp

obj/moc_myimage.o: moc/moc_myimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_myimage.o moc/moc_myimage.cpp

obj/moc_cachecontent.o: moc/moc_cachecontent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_cachecontent.o moc/moc_cachecontent.cpp

obj/moc_settings.o: moc/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_settings.o moc/moc_settings.cpp

obj/moc_netinfo.o: moc/moc_netinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_netinfo.o moc/moc_netinfo.cpp

obj/moc_isclick.o: moc/moc_isclick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_isclick.o moc/moc_isclick.cpp

obj/moc_utility.o: moc/moc_utility.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_utility.o moc/moc_utility.cpp

obj/qrc_image.o: rcc/qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_image.o rcc/qrc_image.cpp

####### Install

install_splash: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/data/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/data/ 
	-$(INSTALL_FILE) d:/ithome/Image/MeeGo.png $(INSTALL_ROOT)/opt/ithome/data/


uninstall_splash:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/data/MeeGo.png
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/data/ 


install_iconsvg: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ 
	-$(INSTALL_FILE) d:/ithome/ithomemeego.svg $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/


uninstall_iconsvg:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ithomemeego.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ 


install_itemfolder_03: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/qml/ 
	-$(INSTALL_DIR) d:/ithome/qml/general $(INSTALL_ROOT)/opt/ithome/qml/


uninstall_itemfolder_03:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/qml/general
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/qml/ 


install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/qml/ 
	-$(INSTALL_DIR) d:/ithome/qml/meego $(INSTALL_ROOT)/opt/ithome/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/qml/meego
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/qml/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) d:/ithome/ithome80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ithome80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) d:/ithome/ithome_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/ithome_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/ithome/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/ithome/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/bin/ 


install:  install_splash install_iconsvg install_itemfolder_03 install_itemfolder_01 install_icon install_desktopfile install_target  FORCE

uninstall: uninstall_splash uninstall_iconsvg uninstall_itemfolder_03 uninstall_itemfolder_01 uninstall_icon uninstall_desktopfile uninstall_target   FORCE

FORCE:

